# If PKOS saves you time, consider sponsoring its maintenance.
# Edit this file once you've set up sponsors on your accounts.

github: [flashfabrixx]
# ko_fi: flashfabrixx
# buy_me_a_coffee: flashfabrixx
# custom: ['https://example.com/donate']
